#!/bin/sh

# Copyright (c) 2015, Expanded Possibilities, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials provided
# with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
#  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
#  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.


BIN_DIR="$1";
TEST_DIR="$BIN_DIR/tests";
shift;

TESTS=$@;

ALL_TESTS='t_findslashes fwatch_help canname_help t_canonicalpath'

if [ -z "$TESTS" ]; then
  TESTS="$ALL_TESTS"
fi

TFAIL=0;
TPASS=0;

function testit() {
  [ -n "$SHOW_TESTS" ] && printf '\n`%s`: ' "$*";
  if "$@"; then
    STPASS=`expr $STPASS + 1`;
    printf 1;
    return 0;
  else
    STFAIL=`expr $STFAIL + 1`;
    printf 0;
    return 1;
  fi
}

for t in $TESTS; do
  STFAIL=0;
  STPASS=0;
  printf "$t ";
  case $t in
    t_findslashes)
      for p in foo/bar/baz \
               /foo/bar/baz \
               //foo/bar/baz \
               /foo//bar/baz \
               /foo/bar/baz/ \
               //foo/bar/baz// \
               /foo//bar/baz// \
               foo \
               ' /foo' \
               'foo/ /' \
               '' ; do
        testit $TEST_DIR/t_findslashes "$p"
      done;;
    t_canonicalpath)
      while read base rel exp; do
        [ "$base" = 'NONE' ] && base='';
        [ "$rel" = 'NONE' ] && rel='';
        testit "$TEST_DIR/t_canonicalpath" "$base" "$rel" "$exp";
      done < "$TEST_DIR/cannames";;
    fwatch_help)
      for h in '--help' '-h'; do
        testit eval "$BIN_DIR/fwatch $h | grep -qi usage"
      done;;
    canname_help)
      for h in '--help' '-h'; do
        testit eval "$BIN_DIR/canname $h | grep -qi usage"
      done;;
    *) echo UNRECOGNIZED TEST;
      testit false;;
  esac
  echo;
  echo "PASS: $STPASS FAIL: $STFAIL";
  TPASS=`expr $TPASS + $STPASS`;
  TFAIL=`expr $TFAIL + $STFAIL`;
  echo;
done

echo "TOTAL_PASS: $TPASS TOTAL_FAIL: $TFAIL";
[ $TFAIL -gt 0 ] && exit 1;
exit 0;